<?php 
$this->title = 'Interface de gestion d\'un administrateur'; 
if (!is_null($data)) {
  $id = $data['id'];
  $pseudo = $data['pseudo'];
  $email = $data['email'];
  $pass = $data['pass'];
}else{
  $id = '';
  $pseudo ='';
  $email = '';
  $pass = '';
}
?>
<div class="row auth">
  <section>
    <fieldset class="col-xs-8 col-xs-offset-2">
        <legend><h2 class="title"><?php if (is_null($data['id'])) {echo "Ajouter un ";}else{echo 'Modifier un ';} ?>administrateur</h2></legend>
        <form class="form-horizontal" action="<?php echo $this->app->getUrl('?interface=admin&controller=admin&action=save');?>" method="post">
            <div class="form-group">
              <label class="control-label col-sm-4" for="pseudo">Pseudo :</label>
              <div class="col-sm-8">
                <input class="form-control" type="text" name="pseudo"  id="pseudo" placeholder="Votre pseudo" required="required" value="<?php echo $pseudo; ?>">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4" for="email">Adresse email:</label>
              <div class="col-sm-8">
                <input class="form-control" type="email" name="email"  id="email" placeholder="Entrer votre adresse email" required="required" value="<?php echo $email; ?>">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-4" for="pass1">Mot de passe :</label>
              <div class="col-sm-8"> 
                <input type="password" class="form-control" id="pass1" name="pass" required="" placeholder="Entrer votre mot de passe" value="<?php echo $pass; ?>">
              </div>
            </div>
            <div id="passError" class="form-group">
              <label class="control-label col-sm-4" for="pass2">Confirmer votre mot de passe :</label>
              <div class="col-sm-8"> 
                <input type="password" class="form-control" id="pass2" name="pass2" required="" aria-describedby="inputError2Status" placeholder="Entrer à nouveau votre mot de passe" value="<?php echo $pass; ?>">
                <span id="glyph" class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
              </div>
            </div>
            <input type="hidden" name="id" value="<?php echo $id; ?>">
            <div class="form-group"> 
              <div class="col-sm-2 col-sm-offset-4">
                  <button id="validation" type="submit" class="btn btn-default"><?php if (is_null($data['id'])) {echo "Ajouter";}else{echo 'Modifier';} ?></button>
              </div>
              <div class="col-sm-2">
                 <button class="btn btn-danger"><a class="annulation" href="<?php echo $this->app->getUrl('?interface=admin&controller=admin&action=record');?>">Annulation</a></button>
              </div>
            </div>
        </form>
    </fieldset> 
  </section>    
</div>
