<?php 
	$this->title = 'Administration : Identification'; 
?>
<div class="row auth">
	<section>
		<fieldset class="col-xs-8 col-xs-offset-2">
				<legend><h2 class="title">Bienvenue sur la page d'authentification de la partie administrateur du site</h2></legend>
				<form class="form-horizontal" action="<?php echo $this->app->getUrl('?interface=admin&controller=authAdmin&action=login');?>" method="post">
					<div class="form-group">
						<label class="control-label col-sm-2" for="pseudo">Pseudo :</label>
						<div class="col-sm-10">
					 		<input type="text" class="form-control" id="pseudo" name="pseudo" required="" placeholder="Entrer votre pseudo">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-sm-2" for="pass">Mot de passe :</label>
						<div class="col-sm-10"> 
							<input type="password" class="form-control" id="pass" name="pass" required="" placeholder="Entrer votre mot de passe">
						</div>
					</div>
					<div class="form-group"> 
						<div class="col-sm-offset-2 col-sm-8 col-sm-offset-2">
					  		<button type="submit" class="btn btn-default">Connection</button>
						</div>
					</div>
				</form>
		</fieldset>	
	</section>	 	
</div>



