<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $title ?></title>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700|Lora:400,400i,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="<?php echo 'web/css/style.css?' . time(); ?>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo 'web/js/script.js?' . time(); ?>"></script> 
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">
    <noscript>
        <div class="row">
            <div id="noJavascript" class="alert alert-danger fade in">       
                <strong>Attention javascript n'est pas activé !</strong>
                <p>Sans son activavation, la plupart des fonctionnalités de l'interface administrateur ne seront pas disponibles.</p>
                <p>Veuillez cliquer sur ce <a href="http://www.libellules.ch/dotclear/index.php?post/2015/05/17/Activer-ou-desactiver-JavaScript-dans-votre-navigateur">lien</a> et suivre les instructions pour votre navigateur.</p>      
            </div> 
        </div>
    </noscript>
    <div id="content" class="container-fluid">
        <div class="row" id="home">
            <header>
                <nav class="navbar navbar-default navbar-fixed-top">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span> 
                            </button>
                            <a class="navbar-brand" href="<?php echo $this->app->getUrl('?controller=home&action=index#home');?>"><i class="glyphicon glyphicon-home"></i> Jean Forteroche</a>
                        </div>
                        <div class="collapse navbar-collapse" id="myNavbar">
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="<?php echo $this->app->getUrl('?controller=article&action=index');?>"><i class="glyphicon glyphicon-book"></i> Chapitres</a></li>
                                <li><a href="<?php echo $this->app->getUrl('?controller=home&action=index#biographie');?>"><i class="glyphicon glyphicon-info-sign"></i> Biographie</a></li> 
                                <li>
                                    <?php if (!empty($_SESSION['userId'])) {?>
                                    <a href="<?php echo $this->app->getUrl('?controller=authUser&action=logout');?>"><span class="glyphicon glyphicon-off"></span> Déconnection</a>
                                    <?php }else{?>
                                    <a href="<?php echo $this->app->getUrl('?controller=authUser&action=auth');?>"><span class="glyphicon glyphicon-log-in"></span> Connection</a>
                                </li>
                                <li><a href="<?php echo $this->app->getUrl('?controller=user&action=registration');?>"><span class="glyphicon glyphicon-user"></span> Inscription</a></li>
                                <?php } ?>  
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        </div>
        <div class="row">
            <?php if (!is_null($this->app->getSuccessMessage())) { ?>
            <div class="alert alert-success alert-dismissable fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <i class="icon icon-check-circle icon-lg"></i>
                <strong>Succès !</strong> <?php echo $this->app->getSuccessMessage(); ?>
            </div>
            <?php $this->app->deleteMessage(); ?>
            <?php } ?>
            <?php if (!is_null($this->app->getErrorMessage())) { ?>
            <div class="alert alert-danger alert-dismissable fade in">       
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <i class="icon icon-times-circle icon-lg"></i>
                <strong>Erreur !</strong> <?php echo $this->app->getErrorMessage() ?>.
            </div> 
            <?php $this->app->deleteMessage(); ?>      
            <?php } ?> 
        </div>
        <div class="row">
           <?= $content ?>
       </div>
       <div class="row">
        <footer>
            <p>Site réalisé par Florian Garcia</p>
        </footer>  
    </div>
</div>
</body>
</html>
