<?php 
$this->title = 'Interface de gestion des articles'; 
?>
<div class="row">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2">
    <h2 class="title">Liste de tous les articles</h2>
      <table class="table table-hover table-condensed">
        <thead>
          <tr>
            <th>Titre</th>
            <th>Auteur</th>
            <th>Date Article</th>
            <th>Action</th>
            <th>Brouillon</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($data as $key => $value){ ?>

          <tr id="<?php echo 'tr' . $data[$key]['id'] ?>" <?php if (!is_null($data[$key]['isDraft'])) {echo 'class="danger"';}?>>
              <td><? echo $data[$key]['title'];?></td>
              <td><? echo $data[$key]['adminPseudo'];?></td>
              <td><? echo $data[$key]['dateArticle'];?></td>
              <td> 
                 <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#modalArticle" data-whatever="<?php echo $data[$key]['id'] ?>">Supprimer</button>
                  <a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=record&id=' . $data[$key]['id']);?>"><button class="btn btn-default btn-xs">Modifier</button></a>
                  <a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=show&id=' . $data[$key]['id']);?>"><button class="btn btn-default btn-xs">Vue</button></a>     
              </td>
              <td>
                <div class="onoffswitch">
                    <input type="checkbox" value="<?php echo $data[$key]['id']; ?>" name="isDraft" class="onoffswitch-checkbox buttonDraft" id="<?php echo 'isDraft' . $data[$key]['id'] ?>" <?php if(!is_null($data[$key]['isDraft'])){echo 'checked';}?>>
                    <label class="onoffswitch-label" for="<?php echo 'isDraft' . $data[$key]['id'] ?>">
                        <span class="onoffswitch-inner"></span>
                        <span class="onoffswitch-switch"></span>
                    </label>
                </div>
              </td>
          </tr>
          </div>
          <?php } ?>
        </tbody>
      </table>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="modalArticle" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
       <div class="alert alert-danger">       
           <i class="icon icon-times-circle icon-lg"></i>
           <strong>Attention !</strong><p>Êtes-vous sûr de vouloir supprimer cet article ?</p>
       </div> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a href=""><button class="btn btn-danger" data-toggle="modal" data-target="#myModal">Supprimer</button></a>
      </div>
    </div>
  </div>
