<?php 
$this->title = 'Admin : ' . $data['article']['title']; 
?>
<div class="row">
	<div class="col-xs-10 col-xs-offset-1 imgHead">
		<?php if (file_exists('web/img/article/' . $data['article']['id'] . '/main' . $data['article']['id'] .'.jpg')) {?>
		<img src="<?echo 'web/img/article/' . $data['article']['id'] . '//main' . $data['article']['id'] .'.jpg?' . time();?>" alt="Image de couverture">
		<?}else{}?>
	</div>
	<section class="col-sm-8 col-sm-offset-2 article">
	    <div class="title">
	        <h1 class="titreBillet"><?= $data['article']['title'] ?></h1>
	        <time><em>Créé le : <?= $data['article']['dateArticle'] ?></em></time>
	    </div>
	    <div class="vueArticle"><?= $data['article']['content'] ?></div>
	    <div class="row boutonArticle">
	    	<div class="col-xs-2 col-xs-offset-1 precedent">
	    		<?php if (!is_null($data['article']['previousId'])) { ?>
	    			<a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=show&id=' . $data['article']['previousId']);?>"><button class="btn btn-default"><i class="glyphicon glyphicon-arrow-left"></i> <i class="glyphicon glyphicon-align-justify"></i></button></a>
	    		<?php  } ?>
	 
	    	</div>
	    	<div class="col-xs-2 col-xs-offset-2">
	    		<a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=index');?>"><button class="btn btn-default"><i class="glyphicon glyphicon-home"></i></button></a>
	    	</div>
	    	<div class="col-xs-2 col-xs-offset-2 precedent">
    			<?php if (!is_null($data['article']['nextId'])) { ?>
    				<a href="<?php echo $this->app->getUrl('?interface=admin&controller=article&action=show&id=' . $data['article']['nextId']);?>"><button class="btn btn-default"><i class="glyphicon glyphicon-align-justify"></i> <i class="glyphicon glyphicon-arrow-right"></i></button></a>
    			<?php  } ?>
	    	</div>
	    </div>
	</section>
</div>
<div class="row">
	<fieldset class="col-xs-8 col-xs-offset-2">
			<legend>Vos commentaires</legend>
			<?php if (!empty($_SESSION['userId'])) {?>
			<div class="row">
				<form class="col-xs-10 col-xs-offset-1" action="<?php echo $this->app->getUrl('?interface=admin&controller=comment&action=save');?>" method="post">
					<textarea class="form-control" name="content" id="mytextarea" placeholder="Votre commentaire" rows="3" required="required"></textarea>
					<input type="hidden" name="userId" value="<?php  echo $_SESSION['userId']?>">
					<input type="hidden" name="dateComment" value="<?echo date("Y-m-d H:i:s");?>">
					<input type="hidden" name="articleId" value="<? echo $data['article']['id'] ?>">
					<input type="hidden" name="idParent" value="0">
					<br>
					<button type="submit" class="btn btn-default btn-xs">Envoyer</button>
				</form>
			</div>
			<?php } ?>
			<div class="row">
				<?php foreach ($data['comments'] as $key => $value) {
						if (isset($data['comments'][$key]['id'])) { ?>
							<!-- Vue d'un commentaire de degré 1-->
							<div class="row">
								<div class="col-xs-12">
									<div class="well well-sm">
										<div class="row">
											<div class="col-md-5 col-xs-6">
												<p><strong class="badge"><?= $data['comments'][$key]['userPseudo'] ?></strong></p>
											</div>
											<div class="col-md-5 col-md-offset-2 col-xs-6">
												<small><em> Le : <?= $data['comments'][$key]['dateComment'] ?></em></small>
											</div>
										</div>
										<div class="row">
											<div class="col-xs-12">
												<p><?= $data['comments'][$key]['content'] ?></p>
											</div>
										</div>
										<?php if (!empty($_SESSION['userId'])) {?>
											<button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#modalComment1" data-whatever="<?php echo $data['comments'][$key]['id'] . '/' . $data['article']['id'] ?>">Supprimer</button>
											<button class="btn btn-default btn-xs buttonComment">Répondre</button>

										<!-- Interface de réponse à un commentaire activé par le button -->
										<div class="row formComment">
											<form class="col-xs-10 col-xs-offset-2" action="<?php echo $this->app->getUrl('?interface=admin&controller=comment&action=save');?>" method="post">
												<textarea class="form-control" name="content" id="mytextarea" placeholder="Votre réponse au commentaire" rows="3" required="required"></textarea>
												<input type="hidden" name="userId" value="<?php  echo $_SESSION['userId']?>">
												<input type="hidden" name="dateComment" value="<?echo date("Y-m-d H:i:s");?>">
												<input type="hidden" name="articleId" value="<? echo $data['article']['id'] ?>">
												<input type="hidden" name="idParent" value="<? echo $data['comments'][$key]['id'] ?>">
												<br>
												<button type="submit" class="btn btn-default btn-xs">Envoyer</button>
											</form>
										</div>
										<?php } ?>
									</div>
								</div>
							</div>
					<?php 	}else{ ?>
						<!-- Vue si le commentaire a été supprimé -->
						<div class="well">
							<p><strong class="badge">Admin</strong></p>
							<p> Ce commentaire a été supprimé par l'administrateur </p>
						</div>
					<?php } ?>
						<?php if(isset($data['comments'][$key]['response'])){ ?>
							<button class="btn btn-default btn-xs buttonDisplay">Afficher réponses</button>
						<?php } ?>
						<div class="children">
							<?php if (isset($data['comments'][$key]['response'])) {
								foreach ($data['comments'][$key]['response'] as $comment => $com) {?>
								<!-- Vue d'un commentaire de degré 2 -->
								<div class="row">
									<div class="col-xs-11 col-xs-offset-1">
										<div class="well well-sm sousCommentaire">
											<div class="row">
												<div class="col-md-5 col-xs-6">
													<p><strong class="badge"><?= $data['comments'][$key]['response'][$comment]['userPseudo'] ?></strong></p>
												</div>
												<div class="col-md-5 col-md-offset-2 col-xs-6">
													<small><em> Le : <?= $data['comments'][$key]['response'][$comment]['dateComment'] ?></em></small>
												</div>
											</div>
											<div class="row">
												<div class="col-xs-12">
													<p><?= $data['comments'][$key]['response'][$comment]['content'] ?></p>
												</div>
											</div>
											<?php if (!empty($_SESSION['userId']) && isset($data['comments'][$key]['id'])) {?>
												
												<button class="btn btn-default btn-xs buttonComment">Répondre</button>

											<!-- Interface de réponse à un commentaire activé par le button -->
											<div class="row formComment">
												<form class="col-sm-10 col-sm-offset-2" action="<?php echo $this->app->getUrl('?interface=admin&controller=comment&action=save');?>" method="post">
													<textarea class="form-control" name="content" id="mytextarea" placeholder="Votre réponse au commentaire" rows="3" required="required"></textarea>
													<input type="hidden" name="userId" value="<?php  echo $_SESSION['userId']?>">
													<input type="hidden" name="dateComment" value="<?echo date("Y-m-d H:i:s");?>">
													<input type="hidden" name="articleId" value="<? echo $data['article']['id'] ?>">
													<input type="hidden" name="idParent" value="<? echo $data['comments'][$key]['id'] ?>">
													<br>
													<button type="submit" class="btn btn-default btn-xs">Envoyer</button>
												</form>
											</div>
											<?php } ?>
											<button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#modalComment2" data-whatever="<?php echo $data['comments'][$key]['response'][$comment]['id'] . '/' . $data['article']['id'] ?>">Supprimer</button>
										</div>
									</div>
								</div>
							<?php }}  ?>	
						</div>
				<?php }?>
			</div>
	</fieldset>
</div>
<!-- Modal -->
<div class="modal fade" id="modalComment1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
       <div class="alert alert-danger">       
           <i class="icon icon-times-circle icon-lg"></i>
           <strong>Attention !</strong><p>Êtes-vous sûr de vouloir supprimer ce commentaire ?</p>
       </div> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button class="btn btn-danger"><a class="annulation" href="">Supprimer</a></button>	
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="modalComment2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
       <div class="alert alert-danger">       
           <i class="icon icon-times-circle icon-lg"></i>
           <strong>Attention !</strong><p>Êtes-vous sûr de vouloir supprimer ce commentaire ?</p>
       </div> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button class="btn btn-danger"><a class="annulation" href="">Supprimer</a></button>
      </div>
    </div>
  </div>
</div>
