<?php 
	$this->title = 'Utilisateur : Identification'; 
?>
<div class="row auth">
	<section>
		<fieldset class="col-xs-8 col-xs-offset-2">
				<legend><h2 class="title">Bienvenue sur la page d'authentification du Blog</h2></legend>
				<form class="form-horizontal" action="<?php echo $this->app->getUrl('?controller=authUser&action=login');?>" method="post">
					<div class="form-group">
						<label class="control-label col-sm-2" for="pseudo">Pseudo :</label>
						<div class="col-sm-10">
					 		<input type="text" class="form-control" id="pseudo" name="pseudo" required="" placeholder="Entrer votre pseudo" value="<?php if (isset($_COOKIE['pseudo'])) {echo $_COOKIE['pseudo'];} ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-sm-2" for="pass">Mot de passe :</label>
						<div class="col-sm-10"> 
							<input type="password" class="form-control" id="pass" name="pass" required="" placeholder="Entrer votre mot de passe">
						</div>
					</div>
					<div class="form-group"> 
					  	<div class="col-sm-offset-2 col-sm-8 col-sm-offset-2">
					    	<div class="checkbox">
					      		<label for="remember"><input type="checkbox" id="remember" name="remember">Se souvenir de moi ?</label>
					    	</div>
					 	 </div>
					</div>
					<div class="form-group"> 
						<div class="col-sm-offset-2 col-sm-8 col-sm-offset-2">
					  		<button type="submit" class="btn btn-default">Connection</button>
						</div>
					</div>
				</form>
		</fieldset>	
	</section>	 	
</div>
